### ISSUE TITLE
Analysis of Package without using GitHub API 

### ISSUE THREAD

**Issue by MadSons** [MadSons/ECE46100-Team#33]
At least one of your metrics must perform an analysis of the package without using the GitHub
API. To conduct this analysis, you should clone the repository locally
- You might then want to interact with the Git metadata programmatically. If you do so:
o You cannot implement analysis by "shelling out" to the git bash CLI
o Instead, use a Git library, such as isomorphic-git (https://github.com/isomorphic-
git/isomorphic-git).
- You might also choose to analyze the software itself. You might employ a static analysis,
e.g. attempting to parse and walk the AST using a JavaScript parsing tool. You might
also apply a dynamic analysis, e.g. running its test suite and doing something with the
resulting information. If you use dynamic analysis, you may make reasonable
assumptions about the test frameworks being used, e.g. supporting the most popular 1-2
frameworks (bring evidence to justify this).

**Comment by bitNathan** [comment]
We have all the metrics done theoretically but I'm planning on adding to the License Compatibility and maybe Ramup Up metrics by pulling the README and licenses the regexing through them a bit
